-- CREATE DATABASE "cvconnect-core-service";
--
-- CREATE TABLE IF NOT EXISTS attach_file (
--     id BIGSERIAL PRIMARY KEY,
--     original_filename VARCHAR(255) NOT NULL,
--     base_filename VARCHAR(255) NOT NULL,
--     extension VARCHAR(50) NOT NULL,
--     filename VARCHAR(255) NOT NULL,
--     format VARCHAR(100) NULL ,
--     resource_type VARCHAR(100) NOT NULL,
--     secure_url VARCHAR(500) NOT NULL,
--     type VARCHAR(100) NOT NULL,
--     url VARCHAR(500) NOT NULL,
--     public_id VARCHAR(255) NOT NULL,
--     folder VARCHAR(255),
--
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100)
-- );
--
-- CREATE TABLE IF NOT EXISTS organization (
--     id BIGSERIAL PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     logo_id BIGINT,
--     cover_photo_id BIGINT,
--     website VARCHAR(255),
--     staff_count_from INT,
--     staff_count_to INT,
--
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100)
-- );
--
-- CREATE TABLE IF NOT EXISTS industry (
--     id BIGSERIAL PRIMARY KEY,
--
--     code VARCHAR(50) UNIQUE NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100)
-- );
--
-- INSERT INTO industry (code, name, created_by) VALUES
-- ('IT', 'Công nghệ thông tin', 'admin'),
-- ('EDU', 'Giáo dục & Đào tạo', 'admin'),
-- ('FIN', 'Tài chính - Ngân hàng', 'admin'),
-- ('INS', 'Bảo hiểm', 'admin'),
-- ('HEA', 'Y tế & Chăm sóc sức khỏe', 'admin'),
-- ('REA', 'Bất động sản', 'admin'),
-- ('CON', 'Xây dựng', 'admin'),
-- ('MAN', 'Sản xuất - Chế biến', 'admin'),
-- ('TRA', 'Thương mại - Bán lẻ', 'admin'),
-- ('AGR', 'Nông nghiệp & Thủy sản', 'admin'),
-- ('LOG', 'Giao thông vận tải & Logistics', 'admin'),
-- ('ENE', 'Năng lượng', 'admin'),
-- ('TEL', 'Viễn thông', 'admin'),
-- ('MED', 'Truyền thông & Giải trí', 'admin'),
-- ('TOU', 'Du lịch & Khách sạn', 'admin'),
-- ('LAW', 'Luật & Dịch vụ pháp lý', 'admin'),
-- ('HR',  'Nhân sự & Tuyển dụng', 'admin'),
-- ('FOO', 'Thực phẩm & Đồ uống', 'admin'),
-- ('FAS', 'Thời trang & Mỹ phẩm', 'admin'),
-- ('PUB', 'Dịch vụ công (Chính phủ, Hành chính)', 'admin'),
-- ('AUT', 'Ô tô & Công nghiệp phụ trợ', 'admin'),
-- ('AVI', 'Hàng không & Vũ trụ', 'admin'),
-- ('MAR', 'Hàng hải & Đóng tàu', 'admin'),
-- ('ELE', 'Điện tử & Cơ điện tử', 'admin'),
-- ('MEC', 'Cơ khí & Chế tạo máy', 'admin'),
-- ('MIN', 'Khai khoáng & Khoáng sản', 'admin');
--
-- CREATE TABLE IF NOT EXISTS organization_industry (
--     id BIGSERIAL PRIMARY KEY,
--
--     org_id INT NOT NULL,
--     industry_id INT NOT NULL,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     UNIQUE (org_id, industry_id),
--     FOREIGN KEY (org_id) REFERENCES organization (id) ON DELETE CASCADE,
--     FOREIGN KEY (industry_id) REFERENCES industry (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS organization_address (
--     id BIGSERIAL PRIMARY KEY,
--
--     org_id BIGINT NOT NULL,
--     is_headquarter BOOLEAN DEFAULT FALSE,
--     province VARCHAR(150) NOT NULL,  -- Tỉnh/Thành phố
--     district VARCHAR(150), -- Quận/Huyện
--     ward VARCHAR(150), -- Xã/Phường
--     detail_address VARCHAR(255) NOT NULL,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     FOREIGN KEY (org_id) REFERENCES organization (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS process_type (
--     id BIGSERIAL PRIMARY KEY,
--
--     code VARCHAR(50) UNIQUE NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     sort_order INT DEFAULT 0,
--     is_default BOOLEAN DEFAULT FALSE,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100)
-- );
--
-- insert into process_type (code, name, sort_order, is_default, created_by) values
-- ('APPLY', 'Ứng tuyển', 1, true, 'admin'),
-- ('SCAN_CV', 'Lọc hồ sơ', 2, true, 'admin'),
-- ('CONTEST', 'Thi tuyển', 3, true, 'admin'),
-- ('INTERVIEW', 'Phỏng vấn', 4, true, 'admin'),
-- ('OFFER', 'Đề nghị làm việc', 5, true, 'admin'),
-- ('ONBOARD', 'Onboard', 6, true, 'admin');

-- CREATE TABLE IF NOT EXISTS level (
--     id BIGSERIAL PRIMARY KEY,
--
--     code VARCHAR(50) UNIQUE NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     is_default BOOLEAN DEFAULT FALSE,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100)
-- );
--
-- insert into level (code, name, is_default, created_by) values
-- ('INTERN', 'Thực tập sinh', true, 'admin'),
-- ('STAFF', 'Nhân viên', true, 'admin'),
-- ('LEADER', 'Trưởng nhóm', true, 'admin'),
-- ('DEPARTMENT_HEAD', 'Trưởng/Phó phòng', true, 'admin'),
-- ('MANAGER', 'Quản lý', true, 'admin'),
-- ('BRANCH_HEAD', 'Trưởng/Phó chi nhánh', true, 'admin'),
-- ('VICE_DIRECTOR', 'Phó Giám đốc', true, 'admin'),
-- ('DIRECTOR', 'Giám đốc', true, 'admin');

-- CREATE TABLE IF NOT EXISTS department (
--     id BIGSERIAL PRIMARY KEY,
--
--     code VARCHAR(50) NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     org_id BIGINT NOT NULL,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     FOREIGN KEY (org_id) REFERENCES organization (id) ON DELETE CASCADE,
--     CONSTRAINT uq_department_org_code UNIQUE (org_id, code)
-- );

-- CREATE TABLE IF NOT EXISTS position (
--     id BIGSERIAL PRIMARY KEY,
--
--     code VARCHAR(50) NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     department_id BIGINT NOT NULL,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE,
--     CONSTRAINT uq_position_department_code UNIQUE (department_id, code)
-- );
--
-- CREATE TABLE IF NOT EXISTS position_level (
--     id BIGSERIAL PRIMARY KEY,
--
--     name VARCHAR(255) NOT NULL,
--     position_id BIGINT NOT NULL,
--     level_id BIGINT NOT NULL,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE,
--     FOREIGN KEY (level_id) REFERENCES level (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS position_process (
--     id BIGSERIAL PRIMARY KEY,
--
--     name VARCHAR(255) NOT NULL,
--     position_id BIGINT NOT NULL,
--     process_type_id BIGINT NOT NULL,
--     sort_order INT NOT NULL ,
--
--     is_active BOOLEAN DEFAULT TRUE,
--     is_deleted BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITHOUT TIME ZONE,
--     created_by VARCHAR(100),
--     updated_by VARCHAR(100),
--
--     FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE,
--     FOREIGN KEY (process_type_id) REFERENCES process_type (id) ON DELETE CASCADE
-- );

