package com.cvconnect.enums;

import com.cvconnect.constant.Messages;
import lombok.Getter;

@Getter
public enum NotifyTemplate {
    JOB_AD_CREATED(Messages.JOB_AD_CREATED_TITLE, Messages.JOB_AD_CREATED_MESSAGE),
    CANDIDATE_APPLY_JOB_AD(Messages.CANDIDATE_APPLY_JOB_AD_TITLE, Messages.CANDIDATE_APPLY_JOB_AD_MESSAGE),
    HR_VIEWED_CANDIDATE_PROFILE(Messages.HR_VIEWED_CANDIDATE_PROFILE_TITLE, Messages.HR_VIEWED_CANDIDATE_PROFILE_MESSAGE),
    CHANGE_CANDIDATE_PROCESS(Messages.CHANGE_CANDIDATE_PROCESS_TITLE, Messages.CHANGE_CANDIDATE_PROCESS_MESSAGE),
    ELIMINATE_CANDIDATE(Messages.ELIMINATE_CANDIDATE_TITLE, Messages.ELIMINATE_CANDIDATE_MESSAGE),
    CHANGE_ONBOARD_DATE(Messages.CHANGE_ONBOARD_DATE_TITLE, Messages.CHANGE_ONBOARD_DATE_MESSAGE),
    CHANGE_PROCESS_ONBOARD(Messages.CHANGE_PROCESS_ONBOARD_TITLE, Messages.CHANGE_PROCESS_ONBOARD_MESSAGE),
    ELIMINATE_CANDIDATE_NOTIFY_ORG_ADMIN(Messages.ELIMINATE_CANDIDATE_NOTIFY_ORG_ADMIN_TITLE, Messages.ELIMINATE_CANDIDATE_NOTIFY_ORG_ADMIN_MESSAGE),
    ORG_DEACTIVATE_NOTIFICATION(Messages.ORG_DEACTIVATE_NOTIFICATION_TITLE, Messages.ORG_DEACTIVATE_NOTIFICATION_MESSAGE),
    ORG_ACTIVATE_NOTIFICATION(Messages.ORG_ACTIVATE_NOTIFICATION_TITLE, Messages.ORG_ACTIVATE_NOTIFICATION_MESSAGE),
    CREATED_SCHEDULED(Messages.CREATED_SCHEDULED_TITLE, Messages.CREATED_SCHEDULED_MESSAGE)

    ;
    private final String title;
    private final String message;
    NotifyTemplate(String title, String message) {
        this.title = title;
        this.message = message;
    }
}
